# Project Board Sync Configuration
# This is the single source of truth for automation rules.
# Changes here will be applied on the next sync run.

version: '1.0'

project:
  id: 'PVT_kwDOAA37OM4AFuzg'  # Will be configurable via URL in future
  type: 'ProjectV2'
  organization: 'bcgov'
  repositories:
    - action-builder-ghcr
    - nr-nerds
    - quickstart-openshift
    - quickstart-openshift-backends
    - quickstart-openshift-helpers

monitored:
  users:
    - name: 'GITHUB_AUTHOR'
      type: 'env'
      description: 'Current GitHub user from environment'

rules:
  # Rule Set 1: Which Items are Added to Project Board
  board_items:
    - name: "PullRequest by Author"
      description: "Add pull requests authored by monitored user"
      trigger:
        type: "PullRequest"
        condition: "item.author === monitored.user"
      action: "add_to_board"
      skip_if: "item.inProject"

    - name: "PullRequest by Assignment"
      description: "Add pull requests assigned to monitored user"
      trigger:
        type: "PullRequest"
        condition: "item.assignees.includes(monitored.user)"
      action: "add_to_board"
      skip_if: "item.inProject"

    - name: "PullRequest by Repository"
      description: "Add pull requests from monitored repositories"
      trigger:
        type: "PullRequest"
        condition: "monitored.repos.includes(item.repository)"
      action: "add_to_board"
      skip_if: "item.inProject"

    - name: "Issue by Repository"
      description: "Add issues from monitored repositories"
      trigger:
        type: "Issue"
        condition: "monitored.repos.includes(item.repository)"
      action: "add_to_board"
      skip_if: "item.inProject"

  # Rule Set 2: Column Assignment Rules
  columns:
    - name: "PullRequest New to Active"
      description: "Move pull requests from New to Active"
      trigger:
        type: "PullRequest"
        condition: "item.column === 'New'"
      action: "set_column"
      value: "Active"
      skip_if: "item.column !== 'New'"
      validTransitions:
        - from: "New"
          to: "Active"
          conditions: []

    - name: "PullRequest No Column"
      description: "Set new pull requests to Active"
      trigger:
        type: "PullRequest"
        condition: "!item.column"
      action: "set_column"
      value: "Active"
      skip_if: "item.column"
      validTransitions:
        - from: "None"
          to: "Active"
          conditions: []

    - name: "Issue No Column"
      description: "Set new issues to New"
      trigger:
        type: "Issue"
        condition: "!item.column"
      action: "set_column"
      value: "New"
      skip_if: "item.column"
      validTransitions:
        - from: "None"
          to: "New"
          conditions: []

  # Rule Set 3: Sprint Assignment Rules
  sprints:
    - name: "Active Sprint Assignment"
      description: "Assign current sprint in Next/Active columns"
      trigger:
        type: ["PullRequest", "Issue"]
        condition: "item.column === 'Next' || item.column === 'Active'"
      action: "set_sprint"
      value: "current"
      skip_if: "item.sprint === 'current'"

    - name: "Done Sprint Assignment"
      description: "Assign sprint in Done column"
      trigger:
        type: ["PullRequest", "Issue"]
        condition: "item.column === 'Done'"
      action: "set_sprint"
      value: "current"
      skip_if: "item.sprint"

  # Rule Set 4: Linked Issue Rules
  linked_issues:
    - name: "Linked Issue Inheritance"
      description: "Sync linked issues with PR state"
      trigger:
        type: "LinkedIssue"
        condition: "!item.pr.closed && item.pr.merged"
      action: ["inherit_column", "inherit_assignees"]
      skip_if: "item.column === item.pr.column && item.assignees === item.pr.assignees"

  # Rule Set 5: Assignee Rules  
  assignees:
    - name: "Author Assignment"
      description: "Add PR author as assignee"
      trigger:
        type: "PullRequest"
        condition: "item.author === monitored.user"
      action: "add_assignee"
      value: "item.author"
      skip_if: "item.assignees.includes(item.author)"

technical:
  batch_size: 10
  batch_delay_seconds: 1
  update_window_hours: 24
  optimization:
    skip_unchanged: true
    dedup_by_id: true
