name: Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - run: cd project-board-sync && npm install
    - name: Run all tests
      run: |
        cd project-board-sync
        npm test
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Use default project ID for tests
        NODE_ENV: test

    - name: Validate environment defaults
      run: |
        cd project-board-sync
        node test/validation/env-defaults.test.js
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_ENV: test
