name: GH Project Board Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:
    inputs:
      project_url:
        description: 'GitHub project URL (e.g., https://github.com/orgs/bcgov/projects/16)'
        required: false
        default: 'https://github.com/orgs/bcgov/projects/16'
      project_id:
        description: 'GitHub project ID (e.g., PVT_kwDOAA37OM4AFuzg)'
        required: false
        default: 'PVT_kwDOAA37OM4AFuzg'
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: true
        type: boolean

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: project-board-sync
        run: npm ci
        
      - name: Show Project Configuration
        run: |
          echo "Project Configuration:"
          echo "  PROJECT_URL: ${{ github.event.inputs.project_url || 'Not set' }}"
          echo "  PROJECT_ID: ${{ github.event.inputs.project_id || 'Not set' }}"
          echo "  VERBOSE: ${{ github.event.inputs.verbose || 'true' }}"
          echo "  GITHUB_AUTHOR: ${{ github.actor }}"
          echo ""
          echo "The system will use the first available configuration in this order:"
          echo "  1. PROJECT_URL (if set)"
          echo "  2. PROJECT_ID (if set)" 
          echo "  3. project.id from config/rules.yml (fallback)"
        
      - name: Run Validation
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: ${{ github.actor }}
          PROJECT_URL: ${{ github.event.inputs.project_url || '' }}
          PROJECT_ID: ${{ github.event.inputs.project_id || '' }}
          VERBOSE: ${{ github.event.inputs.verbose || 'true' }}
        working-directory: project-board-sync
        run: npm run validate
       
      - name: Run Project Board Sync
        env:
          GITHUB_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: ${{ github.actor }}
          PROJECT_URL: ${{ github.event.inputs.project_url || '' }}
          PROJECT_ID: ${{ github.event.inputs.project_id || '' }}
          VERBOSE: ${{ github.event.inputs.verbose || 'true' }}
        working-directory: project-board-sync
        run: npm run start

      - name: Notify Microsoft Teams on failure
        if: failure() && github.event_name != 'pull_request'
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE=":x: Project Board Sync failed on ${{ github.repository }} (${{ github.workflow }}) [Run ${{ github.run_id }}]. See logs for details."
          PAYLOAD=$(jq -nc \
            --arg type "MessageCard" \
            --arg context "http://schema.org/extensions" \
            --arg summary "Project Board Sync failed" \
            --arg themeColor "FF0000" \
            --arg title "Project Board Sync failed" \
            --arg text "$MESSAGE" \
            '{ "@type": $type, "@context": $context, summary: $summary, themeColor: $themeColor, title: $title, text: $text }')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"
