name: GH Project Assigner

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @octokit/graphql @octokit/rest js-yaml

      - name: Run GH Project Assigner
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: node project-sync/project-sync.js

      - name: Notify Microsoft Teams on failure
        if: failure()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE=":x: GH Project Assigner failed on ${{ github.repository }} (${{ github.workflow }}) [Run ${{ github.run_id }}]. See logs for details."
          PAYLOAD="{\"@type\": \"MessageCard\", \"@context\": \"http://schema.org/extensions\", \"summary\": \"GH Project Assigner failed\", \"themeColor\": \"FF0000\", \"title\": \"GH Project Assigner failed\", \"text\": \"$MESSAGE\"}"
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"

      - name: Create GitHub Issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const assignee = 'DerekRoberts';
            const title = `[GH Project Assigner] Workflow failed on ${{ github.workflow }} (Run ${{ github.run_id }})`;
            const body = `The GH Project Assigner workflow failed.\n\n- **Repository:** ${{ github.repository }}\n- **Workflow:** ${{ github.workflow }}\n- **Run:** [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\n\nSee logs for details.`;
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              assignees: [assignee]
            });
