name: GH Project Project Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run Sprint Assignment Tests
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
        run: |
          echo "Running sprint assignment validation tests..."
          node project-sync/tests/test-sprint-assignment.js
          if [ $? -ne 0 ]; then
            echo "::error::Sprint assignment tests failed! Fix the sprint assignment logic before continuing."
            exit 1
          fi
          echo "Sprint assignment tests passed successfully ✅"
      
      - name: Run Preflight Checks
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          GITHUB_AUTHOR: "DerekRoberts"
        run: |
          echo "Running preflight validation checks..."
          node project-sync/tests/test-preflight-checks.js
          if [ $? -ne 0 ]; then
            echo "::error::Preflight checks failed! Fix configuration issues before continuing."
            exit 1
          fi
          echo "Preflight checks passed successfully ✅"
        
      - name: Run GH Project Assigner
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          VERBOSE: true
        run: node project-sync/project-sync.js  

      - name: Notify Microsoft Teams on failure
        if: failure() && github.event_name != 'pull_request'
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE=":x: GH Project Assigner failed on ${{ github.repository }} (${{ github.workflow }}) [Run ${{ github.run_id }}]. See logs for details."
          PAYLOAD=$(jq -nc \
            --arg type "MessageCard" \
            --arg context "http://schema.org/extensions" \
            --arg summary "GH Project Assigner failed" \
            --arg themeColor "FF0000" \
            --arg title "GH Project Assigner failed" \
            --arg text "$MESSAGE" \
            '{ "@type": $type, "@context": $context, summary: $summary, themeColor: $themeColor, title: $title, text: $text }')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"
