name: GH Project Board Sync

on:
  pull_request:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: project-board-sync
        run: npm ci
        
      - name: Run Tests
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          VERBOSE: true
        working-directory: project-board-sync
        run: npm test
       
      - name: Run Project Board Sync
        env:
          GH_TOKEN: ${{ secrets.PROJECT_SYNC_TOKEN }}
          VERBOSE: true
        working-directory: project-board-sync
        run: npm start

      - name: Notify Microsoft Teams on failure
        if: failure() && github.event_name != 'pull_request'
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
        run: |
          MESSAGE=":x: Project Board Sync failed on ${{ github.repository }} (${{ github.workflow }}) [Run ${{ github.run_id }}]. See logs for details."
          PAYLOAD=$(jq -nc \
            --arg type "MessageCard" \
            --arg context "http://schema.org/extensions" \
            --arg summary "Project Board Sync failed" \
            --arg themeColor "FF0000" \
            --arg title "Project Board Sync failed" \
            --arg text "$MESSAGE" \
            '{ "@type": $type, "@context": $context, summary: $summary, themeColor: $themeColor, title: $title, text: $text }')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$TEAMS_WEBHOOK_URL"
